version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - ./workspace:/home/jovyan/work/
    ports:
      - "8888:8888"
    container_name: jupyter_notebook
    command: "start-notebook.sh --ServerApp.token=''"
    restart: unless-stopped
